#pragma once

#define FOOTER R"###(

#pragma pop_macro("__STDC__")
#pragma pop_macro("_ATL_VER")
#pragma pop_macro("_CHAR_UNSIGNED")
#pragma pop_macro("_CPPLIB_VER")
#pragma pop_macro("_CPPRTTI")
#pragma pop_macro("_CPPUNWIND")
#pragma pop_macro("_DEBUG")
#pragma pop_macro("_DLL")
#pragma pop_macro("_M_ALPHA")
#pragma pop_macro("_M_IX86")
#pragma pop_macro("_M_IA64")
#pragma pop_macro("_M_MPPC")
#pragma pop_macro("_M_MRX000")
#pragma pop_macro("_M_PPC")
#pragma pop_macro("_MANAGED")
#pragma pop_macro("_MFC_VER")
#pragma pop_macro("_MSC_EXTENSIONS")
#pragma pop_macro("_MSC_VER")
#pragma pop_macro("__MSVC_RUNTIME_CHECKS")
#pragma pop_macro("_MT")
//#pragma pop_macro( "_WCHAR_T_DEFINED" )
//#pragma pop_macro( "_NATIVE_WCHAR_T_DEFINED" )
#pragma pop_macro("_WIN32")
#pragma pop_macro("_WIN64")
#pragma pop_macro("_Wp64")
#pragma pop_macro("_DEBUG")
#pragma pop_macro("RELEASE")
#pragma pop_macro("WIN")
)###"
